node {
    
    def pathToServicePom = 'commander-service/pom.xml';
    def mvn = tool 'Default Maven';
    
    try {
        stage("SCM") {
            checkout scm
        }
        
        stage("Service - Build") {
            sh "${mvn}/bin/mvn -f ${pathToPom} clean install -B -U -DskipTests"
        }
        
        stage("Service - Unit tests") {
            sh "${mvn}/bin/mvn -f ${pathToPom} test  -B -U -Dsurefire.useFile=true"
        }
        
        stage("Service - Sonarqube Quality Check") {
            withSonarQubeEnv() {
                sh "${mvn}/bin/mvn clean verify sonar:sonar -Dsonar.projectKey=Sonar_CommandR"
            }
        }
        
    } catch (err) {
        currentBuild.result = 'FAILURE'
    } finally {
        if (currentBuild.result == null) {
            currentBuild.result = 'SUCCESS'
        }
        stage('Slack notification') {
            println("RESULT: " + currentBuild.result);
        }
    }
}
